### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by emanuelevineti** [glaslos/ssdeep#20] opened 2018-11-16 11:10 UTC
Hi,

I'm trying to compute the hash of a very small file (size 28) and I get this panic error:
Note that this happens only if I force the execution with --force

> panic: runtime error: integer divide by zero
> 
> github.com/glaslos/ssdeep.(*ssdeepState).processByte(0xc4202f7798, 0x63)
> 	/../src/github.com/glaslos/ssdeep/ssdeep.go:107 +0x2ee
> github.com/glaslos/ssdeep.(*ssdeepState).process(0xc4202f7798, 0xc4202f7848)
> 	/../src/github.com/glaslos/ssdeep/ssdeep.go:132 +0xbf
> github.com/glaslos/ssdeep.FuzzyReader(0x6fc620, 0xc42040cc20, 0x1c, 0x200, 0xc42024bce0, 0x1c, 0xc42024bc80)
> 	/../src/github.com/glaslos/ssdeep/ssdeep.go:154 +0x2e4
> ....

It looks like a 0 check is missing 
 `106	rh := int(state.rollingState.rollSum())`
`107	if rh%state.blockSize == (state.blockSize - 1) {`

**Comment by glaslos** [comment] 2018-11-20 19:29
The issue is here: https://github.com/glaslos/ssdeep/blob/c17959d65837b88a8c5ceb4b3a0e949df59f161b/ssdeep.go#L162
We are reducing the block size as the current hash string is not matching the minimum requirements. I agree that we shouldn't panic, but you are not going to get a reasonable hash out of such a small file. What do you suggest how we should behave? Return the current hash when the blocksize reaches zero?

**Comment by glaslos** [comment] 2020-01-16 09:18
Fixed in https://github.com/glaslos/ssdeep/releases/tag/v0.3.1

**Closed by glaslos** 2020-01-16 09:18 UTC
